# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-23 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=20)),
                ('jefe', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('cedula', models.CharField(max_length=8)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('I', 'Indefinido')], max_length=1)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=11)),
                ('correo', models.EmailField(max_length=254)),
                ('fumador', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('alergico', models.CharField(max_length=20)),
                ('motivo', models.CharField(max_length=50)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Area')),
            ],
        ),
    ]
